# Generated by Django 3.0.6 on 2020-09-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCode',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
